name: CI on Push and PullRequest

on: [push, pull_request]

jobs:
  ci:
    container: node:latest
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup
        run: |
          npm install -g npm
          cd frontend
          npm ci
          npm run lint
          npm run prettier-ci
          cd ../backend
          npm ci
          npm run prettier-ci
          npm run test
